### ISSUE TITLE
add more extensive readme

### ISSUE THREAD

**Issue by hiaux0** [midnight-animals/net-test-api#3]
- why are we connecting to a remote mongodb? (based on the connection string)
  - how will you share secrets with me/others?
- please add details (or point to a link) about the .net structure 
- what was your approach for this setup?
  - where did you start?
  - what other options have you considered?

**Comment by hiaux0** [comment]
please answer the questions, eg. about mongodb

**Comment by hiaux0** [comment]
also, what is Dev Container actually?
I saw it is a feature from VSCode, rather something docker themselves
![image](https://github.com/midnight-animals/net-test-api/assets/30693990/352925c1-d635-4eb0-a64a-e7717d0fd510)

please link me to documentation, and why you decided it is needed

**Comment by JaclyNolan** [comment]
> also, what is Dev Container actually? I saw it is a feature from VSCode, rather something docker themselves
> 
> please link me to documentation, and why you decided it is needed
> 
> edit: this?: https://containers.dev/ I never had to do anything with dev container, like the BE guys never instructed me to. So somehow I just thought, that you need to setup some extra propes/fields/scripts for docker. I'm not sure I will be using it. Do you see benefits for yourself already? (because you mentioned "I wanted to setup dev containers for you")

Dev container is a Docker container that contains the development environment
The benefit that you receive is you don't have to download any development kit or runtime package. From one-click everything will be set up for you in the container and you don't have to install anything locally.

https://code.visualstudio.com/docs/devcontainers/containers this is the link

**Comment by JaclyNolan** [comment]
> please answer the questions, eg. about mongodb

It is now using the local mongodb container. Last time it was remote because it was easier to connect to a remote db, than figuring out how to set one up in local.

**Comment by hiaux0** [comment]
gotcha ,tyty
